# Generated by Django 3.1.7 on 2021-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
